version: 1
accounts:
- name: oxo
  coins:
  - 20000token
  - 200000000stake
- name: eika
  coins:
  - 10000token
  - 100000000stake
  faucet:
  name: eika
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
validators:
- name: oxo
  bonded: 100000000stake
